language: python
sudo: false

branches: master

cache: pip
install:
  - pip install -r test_app/requirements.txt

before_install:
  - export DJANGO_SETTINGS_MODULE=configuration.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/Blueshoe/djangocms-reversion2
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/Blueshoe/
  - export PYTHONPATH=$PYTHONPATH:/home/travis
  - export PYTHONPATH=$PYTHONPATH:/home/travis/builds/Blueshoe/
  - env

script:
  python test_app/manage.py test
